name: Sysdig - Build, scan, push and upload SARIF report

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '23 1 * * 1'

permissions:
  contents: read

jobs:

  build:

    permissions:
      checks: write # para sysdiglabs/scan-action publicar os checks
      contents: read # para actions/checkout buscar o código
      security-events: write # para github/codeql-action/upload-sarif fazer o upload dos resultados SARIF
      actions: read # apenas necessário para um repositório privado pelo github/codeql-action/upload-sarif para obter o status da execução da ação
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Scan da imagem
      id: scan
      uses: sysdiglabs/scan-action@v5
      with:
        image-tag: sysdiglabs/dummy-vuln-app:latest
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}

    - name: Upload do arquivo SARIF
      if: always() # Executa independentemente do resultado do escaneamento
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ github.workspace }}/sarif.json
